name: Deploy to Azure Container Apps Job
on:
  workflow_dispatch:
  push:
    branches: main

# Add this permissions block
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name blitzdaycontainer

      - name: Build and push image
        run: |
          # Use a dynamic tag based on the commit SHA
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build . -t blitzdaycontainer-ehape0bqf8gfc8ek.azurecr.io/ms-teams-container-job-img:$IMAGE_TAG
          docker push blitzdaycontainer-ehape0bqf8gfc8ek.azurecr.io/ms-teams-container-job-img:$IMAGE_TAG

      - name: Update Container App Job
        run: |
          # Update the container app job with the new image tag
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          az containerapp job update \
            --name ms-teams-container-job
             \
            --resource-group SGABlitzday \
            --image blitzdaycontainer-ehape0bqf8gfc8ek.azurecr.io/ms-teams-container-job-img:$IMAGE_TAG